Repository MasenoHub/masenohub, pull requests merged in 2019-10, with the labels that each got.

#29 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: Read For Review

#32 Minor fix for typos
  events.php
  footer.php
  header.php
  img/appslab.png
  img/partner1.jpg
  img/partner2.jpg
  img/partner3.jpg
  img/partner4.jpg
  img/partner5.jpg
  img/podii.png
  index.php
  projects.php
Labels: Read For Review, enhancement

#37 Changed content on invitation area
  index.php
Labels: ready for merge
